apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    storage: jenkins-restore-pv
  name: jenkins-restore-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: jenkins-restore-pvc
    namespace: devops
  nfs:
    path: /devops/jenkins-200pv/Restore20201013/data/nfs/devops/jenkins-200pv
    server: 192.168.0.1
  persistentVolumeReclaimPolicy: Retain
status:
  phase: Bound
