apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    storage: jenkins-slave-pv
  name: jenkins-slave-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: jenkins-slave-pvc
    namespace: devops
  nfs:
    path: /data/nfs/devops/jenkins-slave-pv
    server: 192.168.1.1
  persistentVolumeReclaimPolicy: Retain

