apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    storage: jenkins-restore-pv
  name: jenkins-restore-pv
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: standard
  capacity:
    storage: 100Gi
  nfs:
    path: /share_8c0fade2_649f_4ca5_aeaa_8fd57904f8d5/data/nfs/devops/jenkins-200pv
    server: 172.25.1.162
  persistentVolumeReclaimPolicy: Retain
